
#define	g_d(x)	((*x)._acctype.d)
#define	s_d(x, y)	((*x)._acctype.d = ((discr)y))
#define	g_flags(x)	((*x)._acctype.flags)
#define	s_flags(x, y)	((*x)._acctype.flags = ((short)y))
#define	g_lineno(x)	((*x)._acctype.lineno)
#define	s_lineno(x, y)	((*x)._acctype.lineno = ((short)y))
#define	g_next(x)	((*x)._acctype.next)
#define	s_next(x, y)	((*x)._acctype.next = ((ac)y))
#define	g_prev(x)	((*x)._acctype.prev)
#define	s_prev(x, y)	((*x)._acctype.prev = ((short)y))
#define	g_tag(x)	((*x)._acctype.tag)
#define	s_tag(x, y)	((*x)._acctype.tag = ((char *)y))
#define	g_enclunit(x)	((*x)._acctype.enclunit)
#define	s_enclunit(x, y)	((*x)._acctype.enclunit = ((ac)y))
#define	g_type_spec(x)	((*x)._acctype.type_spec)
#define	s_type_spec(x, y)	((*x)._acctype.type_spec = ((ac)y))
#define	g_actype(x)	((*x)._acctype.actype)
#define	s_actype(x, y)	((*x)._acctype.actype = ((ac)y))
#define	g_ACC_alloc(x)	((*x)._acctype.ACC_alloc)
#define	s_ACC_alloc(x, y)	((*x)._acctype.ACC_alloc = ((short)y))
#define	g_ACC_offset(x)	((*x)._acctype.ACC_offset)
#define	s_ACC_offset(x, y)	((*x)._acctype.ACC_offset = ((MAXADDR)y))
#define	g_ACC_nform(x)	((*x)._acctype.ACC_nform)
#define	s_ACC_nform(x, y)	((*x)._acctype.ACC_nform = ((short)y))
#define	g_ACC_flags(x)	((*x)._acctype.ACC_flags)
#define	s_ACC_flags(x, y)	((*x)._acctype.ACC_flags = ((short)y))
#define	g_aggtype(x)	((*x)._aggregate.aggtype)
#define	s_aggtype(x, y)	((*x)._aggregate.aggtype = ((ac)y))
#define	g_fcompas(x)	((*x)._aggregate.fcompas)
#define	s_fcompas(x, y)	((*x)._aggregate.fcompas = ((ac)y))
#define	g_context(x)	((*x)._aggregate.context)
#define	s_context(x, y)	((*x)._aggregate.context = ((ac)y))
#define	g_AGG_flags(x)	((*x)._aggregate.AGG_flags)
#define	s_AGG_flags(x, y)	((*x)._aggregate.AGG_flags = ((short)y))
#define	g_AGG_alloc(x)	((*x)._aggregate.AGG_alloc)
#define	s_AGG_alloc(x, y)	((*x)._aggregate.AGG_alloc = ((short)y))
#define	g_AGG_Doff(x)	((*x)._aggregate.AGG_Doff)
#define	s_AGG_Doff(x, y)	((*x)._aggregate.AGG_Doff = ((MAXADDR)y))
#define	g_AGG_Voff(x)	((*x)._aggregate.AGG_Voff)
#define	s_AGG_Voff(x, y)	((*x)._aggregate.AGG_Voff = ((MAXADDR)y))
#define	g_AGG_tablab(x)	((*x)._aggregate.AGG_tablab)
#define	s_AGG_tablab(x, y)	((*x)._aggregate.AGG_tablab = ((short)y))
#define	g_AGG_offset(x)	((*x)._aggregate.AGG_offset)
#define	s_AGG_offset(x, y)	((*x)._aggregate.AGG_offset = ((MAXADDR)y))
#define	g_AGG_index(x)	((*x)._aggregate.AGG_index)
#define	s_AGG_index(x, y)	((*x)._aggregate.AGG_index = ((short)y))
#define	g_types(x)	((*x)._all.types)
#define	s_types(x, y)	((*x)._all.types = ((ac)y))
#define	g_ALL_Doff(x)	((*x)._all.ALL_Doff)
#define	s_ALL_Doff(x, y)	((*x)._all.ALL_Doff = ((MAXADDR)y))
#define	g_ALL_Voff(x)	((*x)._all.ALL_Voff)
#define	s_ALL_Voff(x, y)	((*x)._all.ALL_Voff = ((MAXADDR)y))
#define	g_altype(x)	((*x)._allocator.altype)
#define	s_altype(x, y)	((*x)._allocator.altype = ((ac)y))
#define	g_obtype(x)	((*x)._allocator.obtype)
#define	s_obtype(x, y)	((*x)._allocator.obtype = ((ac)y))
#define	g_ALLO_Doff(x)	((*x)._allocator.ALLO_Doff)
#define	s_ALLO_Doff(x, y)	((*x)._allocator.ALLO_Doff = ((MAXADDR)y))
#define	g_ALLO_Toff(x)	((*x)._allocator.ALLO_Toff)
#define	s_ALLO_Toff(x, y)	((*x)._allocator.ALLO_Toff = ((MAXADDR)y))
#define	g_elemtype(x)	((*x)._arraytype.elemtype)
#define	s_elemtype(x, y)	((*x)._arraytype.elemtype = ((ac)y))
#define	g_findex(x)	((*x)._arraytype.findex)
#define	s_findex(x, y)	((*x)._arraytype.findex = ((ac)y))
#define	g_ARR_alloc(x)	((*x)._arraytype.ARR_alloc)
#define	s_ARR_alloc(x, y)	((*x)._arraytype.ARR_alloc = ((short)y))
#define	g_ARR_flags(x)	((*x)._arraytype.ARR_flags)
#define	s_ARR_flags(x, y)	((*x)._arraytype.ARR_flags = ((short)y))
#define	g_ARR_offset(x)	((*x)._arraytype.ARR_offset)
#define	s_ARR_offset(x, y)	((*x)._arraytype.ARR_offset = ((short)y))
#define	g_ARR_vdsize(x)	((*x)._arraytype.ARR_vdsize)
#define	s_ARR_vdsize(x, y)	((*x)._arraytype.ARR_vdsize = ((short)y))
#define	g_ARR_ndims(x)	((*x)._arraytype.ARR_ndims)
#define	s_ARR_ndims(x, y)	((*x)._arraytype.ARR_ndims = ((short)y))
#define	g_lhs(x)	((*x)._assign.lhs)
#define	s_lhs(x, y)	((*x)._assign.lhs = ((ac)y))
#define	g_rhs(x)	((*x)._assign.rhs)
#define	s_rhs(x, y)	((*x)._assign.rhs = ((ac)y))
#define	g_entity(x)	((*x)._attribute.entity)
#define	s_entity(x, y)	((*x)._attribute.entity = ((ac)y))
#define	g_attr_value(x)	((*x)._attribute.attr_value)
#define	s_attr_value(x, y)	((*x)._attribute.attr_value = ((short)y))
#define	g_ATTR_Doff(x)	((*x)._attribute.ATTR_Doff)
#define	s_ATTR_Doff(x, y)	((*x)._attribute.ATTR_Doff = ((MAXADDR)y))
#define	g_fact(x)	((*x)._entrycall.fact)
#define	s_fact(x, y)	((*x)._entrycall.fact = ((ac)y))
#define	g_e_num(x)	((*x)._entrycall.e_num)
#define	s_e_num(x, y)	((*x)._entrycall.e_num = ((short)y))
#define	g_e_entry(x)	((*x)._entrycall.e_entry)
#define	s_e_entry(x, y)	((*x)._entrycall.e_entry = ((ac)y))
#define	g_call_delay(x)	((*x)._entrycall.call_delay)
#define	s_call_delay(x, y)	((*x)._entrycall.call_delay = ((ac)y))
#define	g_call_stats(x)	((*x)._entrycall.call_stats)
#define	s_call_stats(x, y)	((*x)._entrycall.call_stats = ((ac)y))
#define	g_call_next(x)	((*x)._entrycall.call_next)
#define	s_call_next(x, y)	((*x)._entrycall.call_next = ((ac)y))
#define	g_fblockloc(x)	((*x)._block.fblockloc)
#define	s_fblockloc(x, y)	((*x)._block.fblockloc = ((ac)y))
#define	g_BLK_stats(x)	((*x)._block.BLK_stats)
#define	s_BLK_stats(x, y)	((*x)._block.BLK_stats = ((ac)y))
#define	g_BLK_exh(x)	((*x)._block.BLK_exh)
#define	s_BLK_exh(x, y)	((*x)._block.BLK_exh = ((ac)y))
#define	g_BLK_SToff(x)	((*x)._block.BLK_SToff)
#define	s_BLK_SToff(x, y)	((*x)._block.BLK_SToff = ((MAXADDR)y))
#define	g_BLK_Moff(x)	((*x)._block.BLK_Moff)
#define	s_BLK_Moff(x, y)	((*x)._block.BLK_Moff = ((MAXADDR)y))
#define	g_BLK_MCoff(x)	((*x)._block.BLK_MCoff)
#define	s_BLK_MCoff(x, y)	((*x)._block.BLK_MCoff = ((MAXADDR)y))
#define	g_CALL_Doff(x)	((*x)._call.CALL_Doff)
#define	s_CALL_Doff(x, y)	((*x)._call.CALL_Doff = ((MAXADDR)y))
#define	g_CALL_Voff(x)	((*x)._call.CALL_Voff)
#define	s_CALL_Voff(x, y)	((*x)._call.CALL_Voff = ((MAXADDR)y))
#define	g_thunk(x)	((*x)._callthunk.thunk)
#define	s_thunk(x, y)	((*x)._callthunk.thunk = ((ac)y))
#define	g_caseexpr(x)	((*x)._case.caseexpr)
#define	s_caseexpr(x, y)	((*x)._case.caseexpr = ((ac)y))
#define	g_CASE_items(x)	((*x)._case.CASE_items)
#define	s_CASE_items(x, y)	((*x)._case.CASE_items = ((ac)y))
#define	g_CASE_Voff(x)	((*x)._case.CASE_Voff)
#define	s_CASE_Voff(x, y)	((*x)._case.CASE_Voff = ((MAXADDR)y))
#define	g_SELECT_items(x)	((*x)._taskselect.SELECT_items)
#define	s_SELECT_items(x, y)	((*x)._taskselect.SELECT_items = ((ac)y))
#define	g_SEL_actuals(x)	((*x)._taskselect.SEL_actuals)
#define	s_SEL_actuals(x, y)	((*x)._taskselect.SEL_actuals = ((short)y))
#define	g_SEL_caller(x)	((*x)._taskselect.SEL_caller)
#define	s_SEL_caller(x, y)	((*x)._taskselect.SEL_caller = ((short)y))
#define	g_SEL_count(x)	((*x)._taskselect.SEL_count)
#define	s_SEL_count(x, y)	((*x)._taskselect.SEL_count = ((short)y))
#define	g_enuml_ord(x)	((*x)._charlit.enuml_ord)
#define	s_enuml_ord(x, y)	((*x)._charlit.enuml_ord = ((short)y))
#define	g_fcompchoice(x)	((*x)._compassoc.fcompchoice)
#define	s_fcompchoice(x, y)	((*x)._compassoc.fcompchoice = ((ac)y))
#define	g_compexpr(x)	((*x)._compassoc.compexpr)
#define	s_compexpr(x, y)	((*x)._compassoc.compexpr = ((ac)y))
#define	g_CPA_exprlab(x)	((*x)._compassoc.CPA_exprlab)
#define	s_CPA_exprlab(x, y)	((*x)._compassoc.CPA_exprlab = ((short)y))
#define	g_comp(x)	((*x)._discr.comp)
#define	s_comp(x, y)	((*x)._discr.comp = ((ac)y))
#define	g_aggregate(x)	((*x)._discrcons.aggregate)
#define	s_aggregate(x, y)	((*x)._discrcons.aggregate = ((ac)y))
#define	g_fenumlit(x)	((*x)._enumtype.fenumlit)
#define	s_fenumlit(x, y)	((*x)._enumtype.fenumlit = ((ac)y))
#define	g_nenums(x)	((*x)._enumtype.nenums)
#define	s_nenums(x, y)	((*x)._enumtype.nenums = ((short)y))
#define	g_rnam(x)	((*x)._exception.rnam)
#define	s_rnam(x, y)	((*x)._exception.rnam = ((ac)y))
#define	g_EXH_items(x)	((*x)._exhandler.EXH_items)
#define	s_EXH_items(x, y)	((*x)._exhandler.EXH_items = ((ac)y))
#define	g_loopid(x)	((*x)._exit.loopid)
#define	s_loopid(x, y)	((*x)._exit.loopid = ((ac)y))
#define	g_exitcond(x)	((*x)._exit.exitcond)
#define	s_exitcond(x, y)	((*x)._exit.exitcond = ((ac)y))
#define	g_exptype(x)	((*x)._exp.exptype)
#define	s_exptype(x, y)	((*x)._exp.exptype = ((ac)y))
#define	g_primary(x)	((*x)._exp.primary)
#define	s_primary(x, y)	((*x)._exp.primary = ((ac)y))
#define	g_filtype(x)	((*x)._filter.filtype)
#define	s_filtype(x, y)	((*x)._filter.filtype = ((ac)y))
#define	g_constraint(x)	((*x)._filter.constraint)
#define	s_constraint(x, y)	((*x)._filter.constraint = ((ac)y))
#define	g_FLT_alloc(x)	((*x)._filter.FLT_alloc)
#define	s_FLT_alloc(x, y)	((*x)._filter.FLT_alloc = ((short)y))
#define	g_FLT_flags(x)	((*x)._filter.FLT_flags)
#define	s_FLT_flags(x, y)	((*x)._filter.FLT_flags = ((short)y))
#define	g_FLT_offset(x)	((*x)._filter.FLT_offset)
#define	s_FLT_offset(x, y)	((*x)._filter.FLT_offset = ((MAXADDR)y))
#define	g_FLT_valsize(x)	((*x)._filter.FLT_valsize)
#define	s_FLT_valsize(x, y)	((*x)._filter.FLT_valsize = ((MAXADDR)y))
#define	g_FLT_vdoffset(x)	((*x)._filter.FLT_vdoffset)
#define	s_FLT_vdoffset(x, y)	((*x)._filter.FLT_vdoffset = ((MAXADDR)y))
#define	g_looppar(x)	((*x)._forblock.looppar)
#define	s_looppar(x, y)	((*x)._forblock.looppar = ((ac)y))
#define	g_FB_stats(x)	((*x)._forblock.FB_stats)
#define	s_FB_stats(x, y)	((*x)._forblock.FB_stats = ((ac)y))
#define	g_FB_lab(x)	((*x)._forblock.FB_lab)
#define	s_FB_lab(x, y)	((*x)._forblock.FB_lab = ((short)y))
#define	g_genpars(x)	((*x)._gennode.genpars)
#define	s_genpars(x, y)	((*x)._gennode.genpars = ((ac)y))
#define	g_gendum(x)	((*x)._gennode.gendum)
#define	s_gendum(x, y)	((*x)._gennode.gendum = ((ac)y))
#define	g_genunit(x)	((*x)._gennode.genunit)
#define	s_genunit(x, y)	((*x)._gennode.genunit = ((ac)y))
#define	g_genkind(x)	((*x)._genpartype.genkind)
#define	s_genkind(x, y)	((*x)._genpartype.genkind = ((short)y))
#define	g_lab(x)	((*x)._goto.lab)
#define	s_lab(x, y)	((*x)._goto.lab = ((ac)y))
#define	g_IF_items(x)	((*x)._if.IF_items)
#define	s_IF_items(x, y)	((*x)._if.IF_items = ((ac)y))
#define	g_delay_expr(x)	((*x)._delay.delay_expr)
#define	s_delay_expr(x, y)	((*x)._delay.delay_expr = ((ac)y))
#define	g_forused(x)	((*x)._foruse.forused)
#define	s_forused(x, y)	((*x)._foruse.forused = ((ac)y))
#define	g_useexpr(x)	((*x)._foruse.useexpr)
#define	s_useexpr(x, y)	((*x)._foruse.useexpr = ((ac)y))
#define	g_abortedtask(x)	((*x)._abortstat.abortedtask)
#define	s_abortedtask(x, y)	((*x)._abortstat.abortedtask = ((ac)y))
#define	g_ifcond(x)	((*x)._ifitem.ifcond)
#define	s_ifcond(x, y)	((*x)._ifitem.ifcond = ((ac)y))
#define	g_IF_stats(x)	((*x)._ifitem.IF_stats)
#define	s_IF_stats(x, y)	((*x)._ifitem.IF_stats = ((ac)y))
#define	g_inexpr(x)	((*x)._in.inexpr)
#define	s_inexpr(x, y)	((*x)._in.inexpr = ((ac)y))
#define	g_intype(x)	((*x)._in.intype)
#define	s_intype(x, y)	((*x)._in.intype = ((ac)y))
#define	g_complete(x)	((*x)._incomplete.complete)
#define	s_complete(x, y)	((*x)._incomplete.complete = ((ac)y))
#define	g_fidiscr(x)	((*x)._incomplete.fidiscr)
#define	s_fidiscr(x, y)	((*x)._incomplete.fidiscr = ((ac)y))
#define	g_indextype(x)	((*x)._index.indextype)
#define	s_indextype(x, y)	((*x)._index.indextype = ((ac)y))
#define	g_frange(x)	((*x)._indexcons.frange)
#define	s_frange(x, y)	((*x)._indexcons.frange = ((ac)y))
#define	g_farg(x)	((*x)._indexing.farg)
#define	s_farg(x, y)	((*x)._indexing.farg = ((ac)y))
#define	g_indir(x)	((*x)._indirect.indir)
#define	s_indir(x, y)	((*x)._indirect.indir = ((ac)y))
#define	g_xxx2(x)	((*x)._internal.xxx2)
#define	s_xxx2(x, y)	((*x)._internal.xxx2 = ((ac)y))
#define	g_ind(x)	((*x)._internal.ind)
#define	s_ind(x, y)	((*x)._internal.ind = ((byte)y))
#define	g_labeldecl(x)	((*x)._labdef.labeldecl)
#define	s_labeldecl(x, y)	((*x)._labdef.labeldecl = ((ac)y))
#define	g_littype(x)	((*x)._literal.littype)
#define	s_littype(x, y)	((*x)._literal.littype = ((ac)y))
#define	g_val(x)	((*x)._literal.val)
#define	s_val(x, y)	((*x)._literal.val = ((lit_ptr)y))
#define	g_LIT_Voff(x)	((*x)._literal.LIT_Voff)
#define	s_LIT_Voff(x, y)	((*x)._literal.LIT_Voff = ((MAXADDR)y))
#define	g_LIT_Doff(x)	((*x)._literal.LIT_Doff)
#define	s_LIT_Doff(x, y)	((*x)._literal.LIT_Doff = ((MAXADDR)y))
#define	g_looplocals(x)	((*x)._loopblock.looplocals)
#define	s_looplocals(x, y)	((*x)._loopblock.looplocals = ((ac)y))
#define	g_cond(x)	((*x)._loopblock.cond)
#define	s_cond(x, y)	((*x)._loopblock.cond = ((ac)y))
#define	g_LPB_stats(x)	((*x)._loopblock.LPB_stats)
#define	s_LPB_stats(x, y)	((*x)._loopblock.LPB_stats = ((ac)y))
#define	g_LPB_lab(x)	((*x)._loopblock.LPB_lab)
#define	s_LPB_lab(x, y)	((*x)._loopblock.LPB_lab = ((short)y))
#define	g_old_type(x)	((*x)._newtype.old_type)
#define	s_old_type(x, y)	((*x)._newtype.old_type = ((ac)y))
#define	g_mark(x)	((*x)._newtype.mark)
#define	s_mark(x, y)	((*x)._newtype.mark = ((short)y))
#define	g_enlits(x)	((*x)._newtype.enlits)
#define	s_enlits(x, y)	((*x)._newtype.enlits = ((ac)y))
#define	g_xxyy(x)	((*x)._inherit.xxyy)
#define	s_xxyy(x, y)	((*x)._inherit.xxyy = ((ac)y))
#define	g_inh_type(x)	((*x)._inherit.inh_type)
#define	s_inh_type(x, y)	((*x)._inherit.inh_type = ((ac)y))
#define	g_inh_oper(x)	((*x)._inherit.inh_oper)
#define	s_inh_oper(x, y)	((*x)._inherit.inh_oper = ((ac)y))
#define	g_is_hidden(x)	((*x)._inherit.is_hidden)
#define	s_is_hidden(x, y)	((*x)._inherit.is_hidden = ((short)y))
#define	g_fentity(x)	((*x)._name.fentity)
#define	s_fentity(x, y)	((*x)._name.fentity = ((ac)y))
#define	g_foperation(x)	((*x)._name.foperation)
#define	s_foperation(x, y)	((*x)._name.foperation = ((ac)y))
#define	g_parname(x)	((*x)._namedass.parname)
#define	s_parname(x, y)	((*x)._namedass.parname = ((ac)y))
#define	g_nexp(x)	((*x)._namedass.nexp)
#define	s_nexp(x, y)	((*x)._namedass.nexp = ((ac)y))
#define	g_objtype(x)	((*x)._objdesc.objtype)
#define	s_objtype(x, y)	((*x)._objdesc.objtype = ((ac)y))
#define	g_expr(x)	((*x)._objdesc.expr)
#define	s_expr(x, y)	((*x)._objdesc.expr = ((ac)y))
#define	g_object_spec(x)	((*x)._object.object_spec)
#define	s_object_spec(x, y)	((*x)._object.object_spec = ((ac)y))
#define	g_desc(x)	((*x)._object.desc)
#define	s_desc(x, y)	((*x)._object.desc = ((ac)y))
#define	g_OBJ_alloc(x)	((*x)._object.OBJ_alloc)
#define	s_OBJ_alloc(x, y)	((*x)._object.OBJ_alloc = ((short)y))
#define	g_OBJ_offset(x)	((*x)._object.OBJ_offset)
#define	s_OBJ_offset(x, y)	((*x)._object.OBJ_offset = ((MAXADDR)y))
#define	g_OBJ_descoff(x)	((*x)._object.OBJ_descoff)
#define	s_OBJ_descoff(x, y)	((*x)._object.OBJ_descoff = ((MAXADDR)y))
#define	g_fvisitem(x)	((*x)._package.fvisitem)
#define	s_fvisitem(x, y)	((*x)._package.fvisitem = ((ac)y))
#define	g_priv(x)	((*x)._package.priv)
#define	s_priv(x, y)	((*x)._package.priv = ((ac)y))
#define	g_pack_body(x)	((*x)._package.pack_body)
#define	s_pack_body(x, y)	((*x)._package.pack_body = ((ac)y))
#define	g_PS_Moff(x)	((*x)._package.PS_Moff)
#define	s_PS_Moff(x, y)	((*x)._package.PS_Moff = ((MAXADDR)y))
#define	g_PS_MCoff(x)	((*x)._package.PS_MCoff)
#define	s_PS_MCoff(x, y)	((*x)._package.PS_MCoff = ((MAXADDR)y))
#define	g_fentry(x)	((*x)._tasktype.fentry)
#define	s_fentry(x, y)	((*x)._tasktype.fentry = ((ac)y))
#define	g_taskbody(x)	((*x)._tasktype.taskbody)
#define	s_taskbody(x, y)	((*x)._tasktype.taskbody = ((ac)y))
#define	g_TSKT_alloc(x)	((*x)._tasktype.TSKT_alloc)
#define	s_TSKT_alloc(x, y)	((*x)._tasktype.TSKT_alloc = ((short)y))
#define	g_TSKT_offset(x)	((*x)._tasktype.TSKT_offset)
#define	s_TSKT_offset(x, y)	((*x)._tasktype.TSKT_offset = ((MAXADDR)y))
#define	g_TSKT_flags(x)	((*x)._tasktype.TSKT_flags)
#define	s_TSKT_flags(x, y)	((*x)._tasktype.TSKT_flags = ((short)y))
#define	g_specif(x)	((*x)._packbody.specif)
#define	s_specif(x, y)	((*x)._packbody.specif = ((ac)y))
#define	g_fbodyloc(x)	((*x)._packbody.fbodyloc)
#define	s_fbodyloc(x, y)	((*x)._packbody.fbodyloc = ((ac)y))
#define	g_PB_stats(x)	((*x)._packbody.PB_stats)
#define	s_PB_stats(x, y)	((*x)._packbody.PB_stats = ((ac)y))
#define	g_PB_exh(x)	((*x)._packbody.PB_exh)
#define	s_PB_exh(x, y)	((*x)._packbody.PB_exh = ((ac)y))
#define	g_PBDY_SToff(x)	((*x)._packbody.PBDY_SToff)
#define	s_PBDY_SToff(x, y)	((*x)._packbody.PBDY_SToff = ((MAXADDR)y))
#define	g_PB_Moff(x)	((*x)._packbody.PB_Moff)
#define	s_PB_Moff(x, y)	((*x)._packbody.PB_Moff = ((MAXADDR)y))
#define	g_PB_MCoff(x)	((*x)._packbody.PB_MCoff)
#define	s_PB_MCoff(x, y)	((*x)._packbody.PB_MCoff = ((MAXADDR)y))
#define	g_subexpr(x)	((*x)._parenths.subexpr)
#define	s_subexpr(x, y)	((*x)._parenths.subexpr = ((ac)y))
#define	g_fprivitem(x)	((*x)._privpart.fprivitem)
#define	s_fprivitem(x, y)	((*x)._privpart.fprivitem = ((ac)y))
#define	g_fpdiscr(x)	((*x)._privtype.fpdiscr)
#define	s_fpdiscr(x, y)	((*x)._privtype.fpdiscr = ((ac)y))
#define	g_impl(x)	((*x)._privtype.impl)
#define	s_impl(x, y)	((*x)._privtype.impl = ((ac)y))
#define	g_exception(x)	((*x)._raise.exception)
#define	s_exception(x, y)	((*x)._raise.exception = ((ac)y))
#define	g_exc_task(x)	((*x)._raise.exc_task)
#define	s_exc_task(x, y)	((*x)._raise.exc_task = ((ac)y))
#define	g_rangetype(x)	((*x)._range.rangetype)
#define	s_rangetype(x, y)	((*x)._range.rangetype = ((ac)y))
#define	g_frang_exp(x)	((*x)._range.frang_exp)
#define	s_frang_exp(x, y)	((*x)._range.frang_exp = ((ac)y))
#define	g_ffield(x)	((*x)._rectype.ffield)
#define	s_ffield(x, y)	((*x)._rectype.ffield = ((ac)y))
#define	g_fvariant(x)	((*x)._rectype.fvariant)
#define	s_fvariant(x, y)	((*x)._rectype.fvariant = ((ac)y))
#define	g_dis(x)	((*x)._rectype.dis)
#define	s_dis(x, y)	((*x)._rectype.dis = ((ac)y))
#define	g_REC_alloc(x)	((*x)._rectype.REC_alloc)
#define	s_REC_alloc(x, y)	((*x)._rectype.REC_alloc = ((short)y))
#define	g_REC_flags(x)	((*x)._rectype.REC_flags)
#define	s_REC_flags(x, y)	((*x)._rectype.REC_flags = ((short)y))
#define	g_REC_offset(x)	((*x)._rectype.REC_offset)
#define	s_REC_offset(x, y)	((*x)._rectype.REC_offset = ((MAXADDR)y))
#define	g_REC_forms(x)	((*x)._rectype.REC_forms)
#define	s_REC_forms(x, y)	((*x)._rectype.REC_forms = ((short)y))
#define	g_REC_vdsize(x)	((*x)._rectype.REC_vdsize)
#define	s_REC_vdsize(x, y)	((*x)._rectype.REC_vdsize = ((short)y))
#define	g_REC_nflds(x)	((*x)._rectype.REC_nflds)
#define	s_REC_nflds(x, y)	((*x)._rectype.REC_nflds = ((short)y))
#define	g_REC_ninits(x)	((*x)._rectype.REC_ninits)
#define	s_REC_ninits(x, y)	((*x)._rectype.REC_ninits = ((short)y))
#define	g_REC_npaths(x)	((*x)._rectype.REC_npaths)
#define	s_REC_npaths(x, y)	((*x)._rectype.REC_npaths = ((short)y))
#define	g_REC_maxpfld(x)	((*x)._rectype.REC_maxpfld)
#define	s_REC_maxpfld(x, y)	((*x)._rectype.REC_maxpfld = ((short)y))
#define	g_REC_vsize(x)	((*x)._rectype.REC_vsize)
#define	s_REC_vsize(x, y)	((*x)._rectype.REC_vsize = ((short)y))
#define	g_REC_pathf(x)	((*x)._rectype.REC_pathf)
#define	s_REC_pathf(x, y)	((*x)._rectype.REC_pathf = ((short)y))
#define	g_rentype(x)	((*x)._renobj.rentype)
#define	s_rentype(x, y)	((*x)._renobj.rentype = ((ac)y))
#define	g_name(x)	((*x)._renobj.name)
#define	s_name(x, y)	((*x)._renobj.name = ((ac)y))
#define	g_ROBJ_alloc(x)	((*x)._renobj.ROBJ_alloc)
#define	s_ROBJ_alloc(x, y)	((*x)._renobj.ROBJ_alloc = ((short)y))
#define	g_ROBJ_offset(x)	((*x)._renobj.ROBJ_offset)
#define	s_ROBJ_offset(x, y)	((*x)._renobj.ROBJ_offset = ((MAXADDR)y))
#define	g_renname(x)	((*x)._renpack.renname)
#define	s_renname(x, y)	((*x)._renpack.renname = ((ac)y))
#define	g_fformal(x)	((*x)._rensub.fformal)
#define	s_fformal(x, y)	((*x)._rensub.fformal = ((ac)y))
#define	g_rettype(x)	((*x)._rensub.rettype)
#define	s_rettype(x, y)	((*x)._rensub.rettype = ((ac)y))
#define	g_subname(x)	((*x)._rensub.subname)
#define	s_subname(x, y)	((*x)._rensub.subname = ((ac)y))
#define	g_enclsub(x)	((*x)._return.enclsub)
#define	s_enclsub(x, y)	((*x)._return.enclsub = ((ac)y))
#define	g_retexpr(x)	((*x)._return.retexpr)
#define	s_retexpr(x, y)	((*x)._return.retexpr = ((ac)y))
#define	g_andthen(x)	((*x)._scc.andthen)
#define	s_andthen(x, y)	((*x)._scc.andthen = ((bool)y))
#define	g_fsccexpr(x)	((*x)._scc.fsccexpr)
#define	s_fsccexpr(x, y)	((*x)._scc.fsccexpr = ((ac)y))
#define	g_SCC_Voff(x)	((*x)._scc.SCC_Voff)
#define	s_SCC_Voff(x, y)	((*x)._scc.SCC_Voff = ((MAXADDR)y))
#define	g_fsetelem(x)	((*x)._set.fsetelem)
#define	s_fsetelem(x, y)	((*x)._set.fsetelem = ((ac)y))
#define	g_iter_ptr(x)	((*x)._set.iter_ptr)
#define	s_iter_ptr(x, y)	((*x)._set.iter_ptr = ((ac)y))
#define	g_stub(x)	((*x)._separate.stub)
#define	s_stub(x, y)	((*x)._separate.stub = ((ac)y))
#define	g_septree(x)	((*x)._separate.septree)
#define	s_septree(x, y)	((*x)._separate.septree = ((ac)y))
#define	g_elem(x)	((*x)._setelem.elem)
#define	s_elem(x, y)	((*x)._setelem.elem = ((ac)y))
#define	g_slrange(x)	((*x)._slice.slrange)
#define	s_slrange(x, y)	((*x)._slice.slrange = ((ac)y))
#define	g_SLI_Doff(x)	((*x)._slice.SLI_Doff)
#define	s_SLI_Doff(x, y)	((*x)._slice.SLI_Doff = ((MAXADDR)y))
#define	g_stub_spec(x)	((*x)._stub.stub_spec)
#define	s_stub_spec(x, y)	((*x)._stub.stub_spec = ((ac)y))
#define	g_LIT_Doff(x)	((*x)._stringlit.LIT_Doff)
#define	s_LIT_Doff(x, y)	((*x)._stringlit.LIT_Doff = ((MAXADDR)y))
#define	g_body_imp(x)	((*x)._sub.body_imp)
#define	s_body_imp(x, y)	((*x)._sub.body_imp = ((ac)y))
#define	g_sub_default(x)	((*x)._sub.sub_default)
#define	s_sub_default(x, y)	((*x)._sub.sub_default = ((ac)y))
#define	g_SUBS_retoff(x)	((*x)._sub.SUBS_retoff)
#define	s_SUBS_retoff(x, y)	((*x)._sub.SUBS_retoff = ((MAXADDR)y))
#define	g_SUBS_alloc(x)	((*x)._sub.SUBS_alloc)
#define	s_SUBS_alloc(x, y)	((*x)._sub.SUBS_alloc = ((short)y))
#define	g_SUBS_offset(x)	((*x)._sub.SUBS_offset)
#define	s_SUBS_offset(x, y)	((*x)._sub.SUBS_offset = ((MAXADDR)y))
#define	g_entry_nr(x)	((*x)._entry.entry_nr)
#define	s_entry_nr(x, y)	((*x)._entry.entry_nr = ((short)y))
#define	g_ENTR_all(x)	((*x)._entry.ENTR_all)
#define	s_ENTR_all(x, y)	((*x)._entry.ENTR_all = ((ac)y))
#define	g_ENTR_off(x)	((*x)._entry.ENTR_off)
#define	s_ENTR_off(x, y)	((*x)._entry.ENTR_off = ((short)y))
#define	g_specif(x)	((*x)._subbody.specif)
#define	s_specif(x, y)	((*x)._subbody.specif = ((ac)y))
#define	g_SBB_stats(x)	((*x)._subbody.SBB_stats)
#define	s_SBB_stats(x, y)	((*x)._subbody.SBB_stats = ((ac)y))
#define	g_SBB_exh(x)	((*x)._subbody.SBB_exh)
#define	s_SBB_exh(x, y)	((*x)._subbody.SBB_exh = ((ac)y))
#define	g_SBB_level(x)	((*x)._subbody.SBB_level)
#define	s_SBB_level(x, y)	((*x)._subbody.SBB_level = ((short)y))
#define	g_SBB_valoff(x)	((*x)._subbody.SBB_valoff)
#define	s_SBB_valoff(x, y)	((*x)._subbody.SBB_valoff = ((MAXADDR)y))
#define	g_SBB_Moff(x)	((*x)._subbody.SBB_Moff)
#define	s_SBB_Moff(x, y)	((*x)._subbody.SBB_Moff = ((MAXADDR)y))
#define	g_SBB_MCoff(x)	((*x)._subbody.SBB_MCoff)
#define	s_SBB_MCoff(x, y)	((*x)._subbody.SBB_MCoff = ((MAXADDR)y))
#define	g_specif(x)	((*x)._taskbody.specif)
#define	s_specif(x, y)	((*x)._taskbody.specif = ((ac)y))
#define	g_task_stats(x)	((*x)._taskbody.task_stats)
#define	s_task_stats(x, y)	((*x)._taskbody.task_stats = ((ac)y))
#define	g_task_exh(x)	((*x)._taskbody.task_exh)
#define	s_task_exh(x, y)	((*x)._taskbody.task_exh = ((ac)y))
#define	g_TSB_Moff(x)	((*x)._taskbody.TSB_Moff)
#define	s_TSB_Moff(x, y)	((*x)._taskbody.TSB_Moff = ((MAXADDR)y))
#define	g_TSB_MCoff(x)	((*x)._taskbody.TSB_MCoff)
#define	s_TSB_MCoff(x, y)	((*x)._taskbody.TSB_MCoff = ((MAXADDR)y))
#define	g_TSB_level(x)	((*x)._taskbody.TSB_level)
#define	s_TSB_level(x, y)	((*x)._taskbody.TSB_level = ((short)y))
#define	g_specif(x)	((*x)._accept.specif)
#define	s_specif(x, y)	((*x)._accept.specif = ((ac)y))
#define	g_accept_stats(x)	((*x)._accept.accept_stats)
#define	s_accept_stats(x, y)	((*x)._accept.accept_stats = ((ac)y))
#define	g_subpr(x)	((*x)._subcall.subpr)
#define	s_subpr(x, y)	((*x)._subcall.subpr = ((ac)y))
#define	g_parenttype(x)	((*x)._subtype.parenttype)
#define	s_parenttype(x, y)	((*x)._subtype.parenttype = ((ac)y))
#define	g_t_stat(x)	((*x)._tagstat.t_stat)
#define	s_t_stat(x, y)	((*x)._tagstat.t_stat = ((ac)y))
#define	g_thexpr(x)	((*x)._thunk.thexpr)
#define	s_thexpr(x, y)	((*x)._thunk.thexpr = ((ac)y))
#define	g_TH_exprlab(x)	((*x)._thunk.TH_exprlab)
#define	s_TH_exprlab(x, y)	((*x)._thunk.TH_exprlab = ((short)y))
#define	g_TH_levlab(x)	((*x)._thunk.TH_levlab)
#define	s_TH_levlab(x, y)	((*x)._thunk.TH_levlab = ((short)y))
#define	g_newtype(x)	((*x)._typeconv.newtype)
#define	s_newtype(x, y)	((*x)._typeconv.newtype = ((ac)y))
#define	g_convexpr(x)	((*x)._typeconv.convexpr)
#define	s_convexpr(x, y)	((*x)._typeconv.convexpr = ((ac)y))
#define	g_TCON_Doff(x)	((*x)._typeconv.TCON_Doff)
#define	s_TCON_Doff(x, y)	((*x)._typeconv.TCON_Doff = ((MAXADDR)y))
#define	g_packname(x)	((*x)._use.packname)
#define	s_packname(x, y)	((*x)._use.packname = ((ac)y))
#define	g_ident(x)	((*x)._unresrec.ident)
#define	s_ident(x, y)	((*x)._unresrec.ident = ((char *)y))
#define	g_ident(x)	((*x)._unreschar.ident)
#define	s_ident(x, y)	((*x)._unreschar.ident = ((char *)y))
#define	g_xxxx(x)	((*x)._variant.xxxx)
#define	s_xxxx(x, y)	((*x)._variant.xxxx = ((ac)y))
#define	g_ffield(x)	((*x)._variant.ffield)
#define	s_ffield(x, y)	((*x)._variant.ffield = ((ac)y))
#define	g_varchoice(x)	((*x)._variant.varchoice)
#define	s_varchoice(x, y)	((*x)._variant.varchoice = ((ac)y))
#define	g_VAR_ffld(x)	((*x)._variant.VAR_ffld)
#define	s_VAR_ffld(x, y)	((*x)._variant.VAR_ffld = ((short)y))
#define	g_VAR_fpath(x)	((*x)._variant.VAR_fpath)
#define	s_VAR_fpath(x, y)	((*x)._variant.VAR_fpath = ((short)y))
#define	g_VAR_fqfld(x)	((*x)._variant.VAR_fqfld)
#define	s_VAR_fqfld(x, y)	((*x)._variant.VAR_fqfld = ((short)y))
#define	g_fwhenchoice(x)	((*x)._whenitem.fwhenchoice)
#define	s_fwhenchoice(x, y)	((*x)._whenitem.fwhenchoice = ((ac)y))
#define	g_WI_stats(x)	((*x)._whenitem.WI_stats)
#define	s_WI_stats(x, y)	((*x)._whenitem.WI_stats = ((ac)y))
#define	g_withunit(x)	((*x)._with.withunit)
#define	s_withunit(x, y)	((*x)._with.withunit = ((ac)y))
#define	g_qualtype(x)	((*x)._qualif.qualtype)
#define	s_qualtype(x, y)	((*x)._qualif.qualtype = ((ac)y))
#define	g_qualexpr(x)	((*x)._qualif.qualexpr)
#define	s_qualexpr(x, y)	((*x)._qualif.qualexpr = ((ac)y))
#define	g_tripsub(x)	((*x)._triple.tripsub)
#define	s_tripsub(x, y)	((*x)._triple.tripsub = ((ac)y))
#define	g_triptype(x)	((*x)._triple.triptype)
#define	s_triptype(x, y)	((*x)._triple.triptype = ((ac)y))
#define	g_tripdtype(x)	((*x)._triple.tripdtype)
#define	s_tripdtype(x, y)	((*x)._triple.tripdtype = ((ac)y))
#define	g_tripnext(x)	((*x)._triple.tripnext)
#define	s_tripnext(x, y)	((*x)._triple.tripnext = ((ac)y))
#define	g_tripmark(x)	((*x)._triple.tripmark)
#define	s_tripmark(x, y)	((*x)._triple.tripmark = ((ac)y))

 /* end of union tree_element */ 
