#define	XSUB	0
#define	XENTRY	1
#define	XPACKAGE	2
#define	XSUBBODY	3
#define	XPACKBODY	4
#define	XTASKBODY	5
#define	XACCEPT	6
#define	XBLOCK	7
#define	XFORBLOCK	8
#define	XLOOPBLOCK	9
#define	XENUMLIT	10
#define	XCHARLIT	11
#define	XTASKTYPE	12
#define	XGENNODE	13
#define	XGENPARTYPE	14
#define	XRECTYPE	15
#define	XVARIANT	16
#define	XINCOMPLETE	17
#define	XPRIVTYPE	18
#define	XRENOBJ	19
#define	XRENPACK	20
#define	XRENSUB	21
#define	XOBJECT	22
#define	XSTUB	23
#define	XENUMTYPE	24
#define	XARRAYTYPE	25
#define	XACCTYPE	26
#define	XSUBTYPE	27
#define	XINHERIT	28
#define	XNEWTYPE	29
#define	XEXCEPTION	30
#define	XPRIVPART	31
#define	XTAGSTAT	32
#define	XINTERNAL	33
#define	XWITH	34
#define	XSEPARATE	35
#define	XOBJDESC	36
#define	XTHUNK	37
#define	XFILTER	38
#define	XUSE	39
#define	XFORUSE	40
#define	XRANGE	41
#define	XINDEX	42
#define	XEXP	43
#define	XSETELEM	44
#define	XCOMPASSOC	45
#define	XNAMEDASS	46
#define	XNAME	47
#define	XSELECT	48
#define	XATTRIBUTE	49
#define	XCALL	50
#define	XENTRYCALL	51
#define	XSLICE	52
#define	XALL	53
#define	XINDEXING	54
#define	XDISCR	55
#define	XINDIRECT	56
#define	XSET	57
#define	XINDEXCONS	58
#define	XDISCRCONS	59
#define	XLITERAL	60
#define	XUNRESREC	61
#define	XUNRESCHAR	62
#define	XAGGREGATE	63
#define	XALLOCATOR	64
#define	XIN	65
#define	XTYPECONV	66
#define	XPARENTHS	67
#define	XSCC	68
#define	XMARK	69
#define	XGOTO	70
#define	XSUBCALL	71
#define	XASSIGN	72
#define	XEXIT	73
#define	XRETURN	74
#define	XIFITEM	75
#define	XWHENITEM	76
#define	XIF	77
#define	XCASE	78
#define	XTASKSELECT	79
#define	XDELAY	80
#define	XTERMINATE	81
#define	XABORTSTAT	82
#define	XRAISE	83
#define	XEXHANDLER	84
#define	XTRIPLE	85
