#define	__AC_CHECK	"__ac_check"
#define	__ADB_BREAK	"__adb_break"
#define	__AND		"__and"
#define	__ASSIGN	"__assign"
#define	__CHECK		"__check"
#define	__CRAISE	"__raise"
#define	__DRAISE	"__t_raise"
#define	__RERAISE	"__reraise"
#define	__DC_CHECK	"__dc_check"
#define	__EQUAL		"__equal"
#define	__ERROR		"__error"
#define	__GE		"__ge"
#define	__GENABORT	"__genabort"
#define	__GR		"__gr"
#define	__HARDRET	"__hardret"
#define	__HINIT		"__hinit"
#define	__HRESTORE	"__hrestore"
#define	__IC_CHECK	"__ic_check"
#define	__INCOMP	"__incomp"
#define	__INDEXING	"__indexing"
#define	__INSCALAR	"__inscalar"
#define	__LE		"__le"
#define	__LESS		"__less"
#define	__NOT		"__not"
#define	__OR		"__or"
#define	__RC_CHECK	"__rc_check"
#define	__REC_INIT	"__rec_init"
#define	__RERAISE	"__reraise"
#define	__SCAL_CHECK	"__scal_check"
#define __SCCCOMP	"__scccom"
#define	__SLICE		"__slice"
#define	__XOR		"__xor"
#define	_AL_FREE	"_al_free"
#define	_ALLOC_1	"_alloc_1"
#define	_ALLOC_1A	"_alloc_1a"
#define	_ALLOC_2	"_alloc_2"
#define	_ALLOC_3	"_alloc_3"
#define	_ALLOC_4	"_alloc_4"
#define	_LARGQUAL	"_largqual"
#define	_R_INIT		"_r_init"
#define	_UNCO_AS	"_unco_as"
#define	_UNCO_DE	"_unco_de"
#define	_UNCO_VA	"_unco_va"

/* tasking kernel interface */

#define	_ACTIVAT	"_activate"
#define	_CALLABL	"_Callable"
#define	_CALL_RD	"_call_rdv"
#define	_CREATE_	"_create_td"
#define	_END_RDV	"_end_rdv"
#define	_LEAVE_M 	"_leave_master"
#define	_LOCK		"_lock"
#define	_NEW_MAS	"_new_master"
#define	_SET_MOD	"_set_mode"
#define	_START_R	"_start_rdv"
#define	_TERMINA	"_terminate"
#define	_tERMINA	"_Terminate"
#define	_UNLOCK		"_unlock"
#define _ZOMBIE		"_zombie"
#define _START_T	"_error_t"
#define	_DELAY		"__delay"

/*
 *	inserted handlers
 */
#define	__PROC_H		"_prochandler"
#define	_BLOCK_H		"_blockhandler"
#define	_ACCEPT_H		"_accepthandler"
#define	_TASK_H			"_taskhandler"

/*
 *	tasking aids
 */
#define	MYSELF		"_myself"
#define _STD_MASTER	"__std_master"
