.mP "CAT"
.NM "cat unit_name"
.MO "main"
.DC
The 'cat' command will list the source of the library unit
with each source line preceded by a line number.
.br
When listing a long library unit the lower left corner of the screen
will display more in reverse video.
By typing the character 'q' you terminate the listing.
By typing any other character you continue the listing of the
library unit.
.ED
.ER
     a nonexisting unit will give an error.
.SE "list"
