.mP "CONTEXT"
.NM "context"
.MO "print"
.DC
The 'context' displays the context of an executed statement
in exactly the same way as the 'cont' command does it.
.br
Be aware that the 'context' command does not execute the DAS
program like the 'cont' command.
.br
The 'context' command is only usable when the last executed event
was the execution of a statement.
.ED
.ER
     last event is not the execution of a statement
.SE "cont , show"
