.mP "DELETE"
.NM "delete"
.MO "main , run , print , trace , break"
.DC
The delete command changes the current mode to delete mode.
.br
The commands available in trace and break mode are also available
in the delete mode.
The effect of the commands 'calls', 'lines' and 'exceptions'
in delete mode is the deletion of trace or break points set
in trace or break mode at events or exceptions.
.ED
.ER
     none.
.SE "trace , break"
