.mP "LAST"
.NM "last"
.MO "print"
.DC
The 'last' command lists the last 15 subprogram calls and package
elaborations.
The most resent subprogram call or package elaboration is given first
in the listing, the last but one call or elaboration is given as the
second in the listing, and so on.
.br
Be aware that this is only a history of the last 15 calls or elaborations
so the listing does not reflect the active subprograms and packages.
.ED
.ER
     none
.SE "stack"

