.mP "RUN"
.NM "run"
.MO "main , run"
.DC
The 'run' command starts the DAS program when the state of the program is
fetched, terminated, aborted or killed.
In all other states the command continues the DAS program.
.br
If the program is started the output region will be cleared
and you will be prompted for arguments.Return stops input.
When the program is executing the state will be running.
.ED
.ER
.SE "step , after , cont , program"
