# maak een hele nieuwe kompijler
PARAM=
all:	
#	cd codgen1;make ${PARAM} install
#	cd cgyaccsrc; make ${PARAM} install
#	cd codgen2; make ${PARAM} install
#	cd veyacc;make ${PARAM}
#	cd libvy;make ${PARAM} install
	cd treetool; make ${PARAM}
#	cd view;make ${PARAM} all
#	cd h;make ${PARAM} 
#	cd front;make ${PARAM} install
#	cd cg;make ${PARAM} install
#	cd adadep;make ${PARAM}
#	cd rt;make ${PARAM}
#	cd standard;make ${PARAM} all
